import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const robotoSans = Roboto({
    variable: "--font-roboto-sans",
    subsets: ["latin"],
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Emotion board",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${robotoSans.className}  antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
